# Generated by Django 5.2 on 2025-04-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("time", models.CharField(max_length=10)),
                ("activity", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("cost", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField()),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="users.itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["day_number", "order"],
            },
        ),
    ]
