# Generated by Django 5.2 on 2025-04-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_activity_latitude_activity_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.JSONField(default=list)),
                (
                    "itinerary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_checklist",
                        to="users.itinerary",
                    ),
                ),
            ],
        ),
    ]
